site_name: SyncEngine docs
repo_url: https://github.com/SyncEngine/SyncEngine-docs
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - For developers:
      - Module development: module-development.md
