site_name: SyncEngine docs
site_url: https://docs.syncengine.io/
site_description: Project documentation for SyncEngine.
repo_url: https://github.com/SyncEngine/SyncEngine-docs
site_author: SyncEngine team
edit_uri: edit/main/docs/
copyright: Copyright &copy; <a href="https://syncengine.io">SyncEngine</a>.
use_directory_urls: false
extra:
  generator: false

nav:
  - Home: 'index.md'
  - User docs:
      - 'Getting started': 'user-docs/getting-started.md'
      - 'Best practices': 'user-docs/best-practices.md'
      - 'SyncEngine tabs':
          - 'Connections': 'user-docs/connections.md'
          - 'Automations': 'user-docs/automations.md'
      - 'FAQ': 'user-docs/faq.md'
  - Developer docs:
      - 'Module development': 'dev-docs/module-development.md'

plugins:
  - search
  - autorefs

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde